.TH ABRAFLEXI-YEARDIGEST 1 "October 2023" "1.0" "AbraFlexi Digest Manual"
.SH NAME
abraflexi-yeardigest \- Generate a yearly digest report from AbraFlexi

.SH SYNOPSIS
.B abraflexi-yeardigest
.RI [ options ]

.SH DESCRIPTION
.B abraflexi-yeardigest
is a command-line tool that generates a yearly digest report from the AbraFlexi system.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display help information and exit.

.TP
.B \-y, \-\-year
Specify the year for which the digest report should be generated. Default is the current year.

.TP
.B \-o, \-\-output
Specify the output file for the digest report. Default is standard output.

.SH EXAMPLES
.TP
Generate a digest report for the year 2022 and save it to a file:
.B abraflexi-yeardigest \-y 2022 \-o report.txt

.SH AUTHOR
Written by Vitex Software.

.SH COPYRIGHT
Copyright \(co 2023 Vitex Software. All rights reserved.
