.TH ABRAFLEXI-WEEKDIGEST 1 "October 2023" "1.0" "User Commands"
.SH NAME
abraflexi-weekdigest \- Generate a weekly digest report from AbraFlexi

.SH SYNOPSIS
.B abraflexi-weekdigest
.RI [ options ]

.SH DESCRIPTION
.B abraflexi-weekdigest
is a command-line tool that generates a weekly digest report from the AbraFlexi system.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display this help and exit.

.TP
.B \-v, \-\-version
Output version information and exit.

.TP
.B \-o, \-\-output
Specify the output file for the digest report.

.TP
.B \-c, \-\-config
Specify the configuration file to use.

.SH EXAMPLES
.TP
Generate a weekly digest and save it to a file:
.B abraflexi-weekdigest \-o report.txt

.TP
Use a specific configuration file:
.B abraflexi-weekdigest \-c config.json

.SH AUTHOR
Written by Vitex Software.

.SH REPORTING BUGS
Report bugs to <support@vitexsoftware.com>.

.SH COPYRIGHT
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
