<?php

namespace Test\AbraFlexi\Digest\Modules;

use AbraFlexi\Digest\Modules\IncomingPayments;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-10-02 at 09:15:15.
 */
class IncomingPaymentsTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var IncomingPayments
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new IncomingPayments();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AbraFlexi\Digest\Modules\IncomingPayments::dig
     * @todo   Implement testdig().
     */
    public function testdig() {
        $this->assertEquals('', $this->object->dig());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Digest\Modules\IncomingPayments::heading
     * @todo   Implement testheading().
     */
    public function testheading() {
        $this->assertEquals('', $this->object->heading());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
