<?php

declare(strict_types=1);

/**
 * This file is part of the AbraFlexi-Digest package
 *
 * https://github.com/VitexSoftware/AbraFlexi-Digest/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi\Digest\Modules;

use AbraFlexi\Digest\Modules\OutcomingInvoicesHiddenToCustomer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-10-02 at 09:15:15.
 */
class OutcomingInvoicesHiddenToCustomerTest extends \PHPUnit\Framework\TestCase
{
    protected OutcomingInvoicesHiddenToCustomer $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new OutcomingInvoicesHiddenToCustomer();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Digest\Modules\OutcomingInvoicesHiddenToCustomer::dig
     *
     * @todo   Implement testdig().
     */
    public function testdig(): void
    {
        $this->assertEquals('', $this->object->dig());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Digest\Modules\OutcomingInvoicesHiddenToCustomer::heading
     *
     * @todo   Implement testheading().
     */
    public function testheading(): void
    {
        $this->assertEquals('', $this->object->heading());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Digest\Modules\OutcomingInvoicesHiddenToCustomer::description
     *
     * @todo   Implement testdescription().
     */
    public function testdescription(): void
    {
        $this->assertEquals('', $this->object->description());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
