<?php

declare(strict_types=1);

/**
 * This file is part of the AbraFlexi-Digest package
 *
 * https://github.com/VitexSoftware/AbraFlexi-Digest/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi\Digest\Modules\Monthly;

use AbraFlexi\Digest\Modules\Monthly\DailyIncomeChart;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-10-02 at 09:15:12.
 */
class DailyIncomeChartTest extends \PHPUnit\Framework\TestCase
{
    protected DailyIncomeChart $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new DailyIncomeChart();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Digest\Modules\Monthly\DailyIncomeChart::dig
     *
     * @todo   Implement testdig().
     */
    public function testdig(): void
    {
        $this->assertEquals('', $this->object->dig());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Digest\Modules\Monthly\DailyIncomeChart::addChartDay
     *
     * @todo   Implement testaddChartDay().
     */
    public function testaddChartDay(): void
    {
        $this->assertEquals('', $this->object->addChartDay());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Digest\Modules\Monthly\DailyIncomeChart::addChartCurrency
     *
     * @todo   Implement testaddChartCurrency().
     */
    public function testaddChartCurrency(): void
    {
        $this->assertEquals('', $this->object->addChartCurrency());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Digest\Modules\Monthly\DailyIncomeChart::addBar
     *
     * @todo   Implement testaddBar().
     */
    public function testaddBar(): void
    {
        $this->assertEquals('', $this->object->addBar());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Digest\Modules\Monthly\DailyIncomeChart::heading
     *
     * @todo   Implement testheading().
     */
    public function testheading(): void
    {
        $this->assertEquals('', $this->object->heading());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
