#!/bin/sh
# postinst script for php-flexibee-digest
WEBUSER="root" 
set -e

    if [ "$1" = "configure" ]; then

    . /usr/share/debconf/confmodule

    fi


mkdir -p /var/lib/composer
chown $WEBUSER:$WEBUSER /var/lib/composer
su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer --no-dev -o install -d /usr/lib/php-flexibee-digest/'

php -f /usr/lib/php-flexibee-digest/Init.php



exit 0
