#!/bin/sh
# postinst script for php-abraflexi-digest
WEBUSER="root" 
set -e

. /usr/share/debconf/confmodule

db_get composer/WEB_USER
WEBUSER=$RET
mkdir -p /var/lib/multi-abraflexi-setup /var/lib/composer
chown $WEBUSER /var/lib/multi-abraflexi-setup /var/lib/composer -R
echo '{}' > /usr/lib/multi-abraflexi-setup/composer.lock
chown $WEBUSER /usr/lib/multi-abraflexi-setup/composer.lock
su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer -o install -d /var/lib/abraflexi-tools/'


#DEBHELPER#

exit 0
