#!/bin/sh
# postinst script for php-abraflexi-digest
WEBUSER="root" 
set -e

. /usr/share/debconf/confmodule

db_get composer/WEB_USER
WEBUSER=$RET
mkdir -p /var/lib/abraflexi-digest /var/lib/composer
chown $WEBUSER /var/lib/abraflexi-digest /var/lib/composer -R
echo '{}' > /usr/lib/abraflexi-digest/composer.lock
chown $WEBUSER /usr/lib/abraflexi-digest/composer.lock
su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer -o update -d /usr/share/abraflexi-digest/'

exit 0
