#!/bin/sh
# postinst script for php-abraflexi-digest
WEBUSER="root" 
set -e

    if [ "$1" = "configure" ]; then

    . /usr/share/debconf/confmodule

    fi


mkdir -p /var/lib/composer 
chown $WEBUSER:$WEBUSER /var/lib/composer
su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer --no-dev -o install -d /usr/share/abraflexi-digest/'

#php -f /usr/lib/php-abraflexi-digest/Init.php

#DEBHELPER#

exit 0
