<?php

namespace Test\AbraFlexi\Digest;

use AbraFlexi\Digest\DocumentTable;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-10-02 at 09:15:16.
 */
class DocumentTableTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var DocumentTable
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new DocumentTable();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }
}
