<?php

declare(strict_types=1);

/**
 * This file is part of the AbraFlexi-Digest package
 *
 * https://github.com/VitexSoftware/AbraFlexi-Digest/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi\Digest;

use AbraFlexi\Digest\Mailer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-10-02 at 09:15:16.
 */
class MailerTest extends \PHPUnit\Framework\TestCase
{
    protected Mailer $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Mailer('test@example.com', 'Test Subject');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Digest\Mailer::addItem
     */
    public function testaddItem(): void
    {
        // Test adding a string item
        $textContent = 'Test email content';
        $result = $this->object->addItem($textContent);
        $this->assertIsString($result);

        // Test adding an HTML object
        $htmlDiv = new \Ease\Html\DivTag('Test HTML content');
        $result = $this->object->addItem($htmlDiv);
        $this->assertNotNull($result);

        // Test adding an array
        $arrayContent = ['Line 1', 'Line 2', 'Line 3'];
        $result = $this->object->addItem($arrayContent);
        $this->assertIsString($result);

        // Test with page item name
        $namedItem = new \Ease\Html\SpanTag('Named content');
        $result = $this->object->addItem($namedItem, 'test-span');
        $this->assertNotNull($result);
    }

    /**
     * @covers \AbraFlexi\Digest\Mailer::getCss
     */
    public function testgetCss(): void
    {
        // getCss() is a void method that does nothing
        // Test that the method exists and is callable
        $this->assertTrue(method_exists($this->object, 'getCss'));
        $this->assertIsCallable([$this->object, 'getCss']);

        // Test that it can be called without errors
        $this->object->getCss();

        // Add an assertion to ensure the test passes
        $this->assertTrue(true, 'getCss method executed without errors');
    }
}
