<?php

namespace Test\AbraFlexi\Digest;

use AbraFlexi\Digest\Table;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-10-02 at 09:15:16.
 * 
 * @deprecated This test is for the deprecated Table class. Use TableTagTest for the new implementation.
 */
class TableTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Table
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Table([_('Test Column 1'), _('Test Column 2')]);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }
}
