<?php

declare(strict_types=1);

/**
 * This file is part of the AbraFlexi-Digest package
 *
 * https://github.com/VitexSoftware/AbraFlexi-Digest/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi\Digest;

use AbraFlexi\Digest\VerticalChart;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-10-02 at 09:15:16.
 */
class VerticalChartTest extends \PHPUnit\Framework\TestCase
{
    protected VerticalChart $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new VerticalChart();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Digest\VerticalChart::addBar
     */
    public function testaddBar(): void
    {
        // Test adding a bar to the chart
        $percent = 75;
        $amount = 1500.50;
        $caption = 'Test Bar';
        $addClass = 'teal';

        // Method returns void, so we test that it doesn't throw errors
        $this->object->addBar($percent, $amount, $caption, $addClass);

        // Test that the method exists and is callable
        $this->assertTrue(method_exists($this->object, 'addBar'));
        $this->assertIsCallable([$this->object, 'addBar']);

        // Add another bar with different parameters
        $this->object->addBar(50, 1000, 'Second Bar', 'salmon');

        // Add another bar with different parameters
        $this->object->addBar(100, 2000, 'Third Bar', 'lime');

        // Since addBar is void method, just verify it completes without exception
        $this->assertTrue(true, 'addBar method executed without errors');
    }
}
